/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudodirigido.formularios;

import com.sun.beans.editors.DoubleEditor;
import estudodirigido.Controle.RepositorioBase;
import estudodirigido.modelo.Disciplina;
import estudodirigido.modelo.Professor;
import estudodirigido.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato
 */
public class FormNotas extends javax.swing.JFrame {
    
    public static RepositorioBase _bd;
    public static Usuario _usuario;
   
    
    
    
    public FormNotas(){
        initComponents();
        this.setSize(610,435);
        setLocationRelativeTo(null);
                
    }
   
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTurma = new javax.swing.JLabel();
        lblAluno5 = new javax.swing.JLabel();
        lblAluno4 = new javax.swing.JLabel();
        lblAluno1 = new javax.swing.JLabel();
        lblAluno2 = new javax.swing.JLabel();
        lblAluno3 = new javax.swing.JLabel();
        txtNota1Aluno1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNota2Aluno1 = new javax.swing.JTextField();
        lblEd = new javax.swing.JLabel();
        txtEdAluno1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNota1Aluno2 = new javax.swing.JTextField();
        txtEdAluno2 = new javax.swing.JTextField();
        txtNota2Aluno2 = new javax.swing.JTextField();
        txtNota1Aluno3 = new javax.swing.JTextField();
        txtNota2Aluno3 = new javax.swing.JTextField();
        txtEdAluno3 = new javax.swing.JTextField();
        txtEdAluno4 = new javax.swing.JTextField();
        txtNota2Aluno4 = new javax.swing.JTextField();
        txtNota1Aluno4 = new javax.swing.JTextField();
        txtNota1Aluno5 = new javax.swing.JTextField();
        txtNota2Aluno5 = new javax.swing.JTextField();
        txtEdAluno5 = new javax.swing.JTextField();
        lblMediaAluno1 = new javax.swing.JLabel();
        lblMediaAluno2 = new javax.swing.JLabel();
        lblMediaAluno3 = new javax.swing.JLabel();
        lblMediaAluno4 = new javax.swing.JLabel();
        lblMediaAluno5 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        lblDisciplina = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        lblTurma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTurma.setText("Turma:");
        getContentPane().add(lblTurma);
        lblTurma.setBounds(25, 20, 160, 14);

        lblAluno5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAluno5.setText("--------------------");
        getContentPane().add(lblAluno5);
        lblAluno5.setBounds(25, 253, 106, 14);

        lblAluno4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAluno4.setText("--------------------");
        getContentPane().add(lblAluno4);
        lblAluno4.setBounds(25, 215, 106, 14);

        lblAluno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAluno1.setText("--------------------");
        getContentPane().add(lblAluno1);
        lblAluno1.setBounds(25, 100, 106, 14);

        lblAluno2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAluno2.setText("--------------------");
        getContentPane().add(lblAluno2);
        lblAluno2.setBounds(25, 138, 106, 14);

        lblAluno3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAluno3.setText("--------------------");
        getContentPane().add(lblAluno3);
        lblAluno3.setBounds(25, 177, 106, 14);

        txtNota1Aluno1.setText("0");
        txtNota1Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1Aluno1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota1Aluno1);
        txtNota1Aluno1.setBounds(173, 97, 37, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NOTA 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(173, 50, 50, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NOTA 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(252, 50, 50, 14);

        txtNota2Aluno1.setText("0");
        txtNota2Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2Aluno1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota2Aluno1);
        txtNota2Aluno1.setBounds(252, 97, 37, 30);

        lblEd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEd.setText("ED");
        getContentPane().add(lblEd);
        lblEd.setBounds(331, 50, 37, 14);

        txtEdAluno1.setText("0");
        txtEdAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdAluno1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdAluno1);
        txtEdAluno1.setBounds(331, 97, 37, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("MÉDIA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(402, 50, 70, 14);

        txtNota1Aluno2.setText("0");
        txtNota1Aluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1Aluno2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota1Aluno2);
        txtNota1Aluno2.setBounds(173, 135, 37, 30);

        txtEdAluno2.setText("0");
        txtEdAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdAluno2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdAluno2);
        txtEdAluno2.setBounds(331, 135, 37, 30);

        txtNota2Aluno2.setText("0");
        txtNota2Aluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2Aluno2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota2Aluno2);
        txtNota2Aluno2.setBounds(252, 135, 37, 30);

        txtNota1Aluno3.setText("0");
        txtNota1Aluno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1Aluno3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota1Aluno3);
        txtNota1Aluno3.setBounds(173, 174, 37, 30);

        txtNota2Aluno3.setText("0");
        getContentPane().add(txtNota2Aluno3);
        txtNota2Aluno3.setBounds(252, 174, 37, 30);

        txtEdAluno3.setText("0");
        getContentPane().add(txtEdAluno3);
        txtEdAluno3.setBounds(331, 174, 37, 30);

        txtEdAluno4.setText("0");
        getContentPane().add(txtEdAluno4);
        txtEdAluno4.setBounds(331, 212, 37, 30);

        txtNota2Aluno4.setText("0");
        getContentPane().add(txtNota2Aluno4);
        txtNota2Aluno4.setBounds(252, 212, 37, 30);

        txtNota1Aluno4.setText("0");
        getContentPane().add(txtNota1Aluno4);
        txtNota1Aluno4.setBounds(173, 212, 37, 30);

        txtNota1Aluno5.setText("0");
        txtNota1Aluno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1Aluno5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNota1Aluno5);
        txtNota1Aluno5.setBounds(173, 250, 37, 30);

        txtNota2Aluno5.setText("0");
        getContentPane().add(txtNota2Aluno5);
        txtNota2Aluno5.setBounds(252, 250, 37, 30);

        txtEdAluno5.setText("0");
        txtEdAluno5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdAluno5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdAluno5);
        txtEdAluno5.setBounds(331, 250, 37, 30);

        lblMediaAluno1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMediaAluno1.setText("0");
        getContentPane().add(lblMediaAluno1);
        lblMediaAluno1.setBounds(408, 103, 34, 14);

        lblMediaAluno2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMediaAluno2.setText("0");
        getContentPane().add(lblMediaAluno2);
        lblMediaAluno2.setBounds(408, 138, 34, 14);

        lblMediaAluno3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMediaAluno3.setText("0");
        getContentPane().add(lblMediaAluno3);
        lblMediaAluno3.setBounds(408, 177, 34, 14);

        lblMediaAluno4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMediaAluno4.setText("0");
        getContentPane().add(lblMediaAluno4);
        lblMediaAluno4.setBounds(408, 215, 34, 14);

        lblMediaAluno5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMediaAluno5.setText("0");
        getContentPane().add(lblMediaAluno5);
        lblMediaAluno5.setBounds(408, 253, 34, 14);

        btnGravar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(380, 340, 120, 23);

        lblDisciplina.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDisciplina.setText("Disciplina:");
        getContentPane().add(lblDisciplina);
        lblDisciplina.setBounds(252, 20, 240, 14);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(20, 340, 120, 23);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(200, 340, 121, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Renato\\Desktop\\2.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNota1Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1Aluno1ActionPerformed
               
        
        
    }//GEN-LAST:event_txtNota1Aluno1ActionPerformed

    private void txtNota2Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2Aluno1ActionPerformed
       
    }//GEN-LAST:event_txtNota2Aluno1ActionPerformed

    private void txtEdAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdAluno1ActionPerformed
       
    }//GEN-LAST:event_txtEdAluno1ActionPerformed

    private void txtNota1Aluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1Aluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1Aluno2ActionPerformed

    private void txtEdAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdAluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdAluno2ActionPerformed

    private void txtNota2Aluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2Aluno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2Aluno2ActionPerformed

    private void txtNota1Aluno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1Aluno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1Aluno3ActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        double nota1=Double.valueOf(txtNota1Aluno1.getText());
        double nota2 =Double.valueOf(txtNota2Aluno1.getText());
        double ed =Double.valueOf(txtEdAluno1.getText());
        //Disciplina d= new Disciplina(nota1, nota2, ed);
        //lblMediaAluno1.setText(String.valueOf(d.calcularMedia(nota1, nota2, ed)));
     
        
        
        
        
     
    }//GEN-LAST:event_btnGravarActionPerformed

    private void txtNota1Aluno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1Aluno5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1Aluno5ActionPerformed

    private void txtEdAluno5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdAluno5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdAluno5ActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        
        FormInicio sair = new FormInicio();
          
        
        sair.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FormHomeProfessor voltar= new FormHomeProfessor(_bd,_usuario);
        
        
        voltar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.out.println();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNotas().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAluno1;
    private javax.swing.JLabel lblAluno2;
    private javax.swing.JLabel lblAluno3;
    private javax.swing.JLabel lblAluno4;
    private javax.swing.JLabel lblAluno5;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblEd;
    private javax.swing.JLabel lblMediaAluno1;
    private javax.swing.JLabel lblMediaAluno2;
    private javax.swing.JLabel lblMediaAluno3;
    private javax.swing.JLabel lblMediaAluno4;
    private javax.swing.JLabel lblMediaAluno5;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JTextField txtEdAluno1;
    private javax.swing.JTextField txtEdAluno2;
    private javax.swing.JTextField txtEdAluno3;
    private javax.swing.JTextField txtEdAluno4;
    private javax.swing.JTextField txtEdAluno5;
    private javax.swing.JTextField txtNota1Aluno1;
    private javax.swing.JTextField txtNota1Aluno2;
    private javax.swing.JTextField txtNota1Aluno3;
    private javax.swing.JTextField txtNota1Aluno4;
    private javax.swing.JTextField txtNota1Aluno5;
    private javax.swing.JTextField txtNota2Aluno1;
    private javax.swing.JTextField txtNota2Aluno2;
    private javax.swing.JTextField txtNota2Aluno3;
    private javax.swing.JTextField txtNota2Aluno4;
    private javax.swing.JTextField txtNota2Aluno5;
    // End of variables declaration//GEN-END:variables
}
