/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudodirigido.formularios;


import Commum.TipoUsuario;
import estudodirigido.Controle.AlunoControle;
import estudodirigido.Controle.CursoControle;
import estudodirigido.Controle.DisciplinaControle;
import estudodirigido.Controle.RepositorioBase;
import estudodirigido.Controle.UsuarioControle;
import estudodirigido.modelo.Aluno;

import estudodirigido.modelo.Curso;
import estudodirigido.modelo.Disciplina;
import estudodirigido.modelo.Usuario;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato
 */
public class FormCadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroAluno
     */
    static int posicao;
    public static RepositorioBase _bd;
    
    
    public FormCadastroAluno(RepositorioBase bd) {
        initComponents();
        this.setVisible(true);
        this.setSize(558, 410);
        this.setLocationRelativeTo(null);
        this._bd=bd;
        
        CarregarCursos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnome = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        lblCpfAluno = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblCadastroAlunos = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        txtCpfAluno = new javax.swing.JFormattedTextField();
        txtDataAluno = new javax.swing.JFormattedTextField();
        txtMat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(558, 356));
        getContentPane().setLayout(null);

        lblnome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnome.setText("Nome:");
        getContentPane().add(lblnome);
        lblnome.setBounds(90, 60, 50, 15);

        txtNomeAluno.setText(" ");
        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeAluno);
        txtNomeAluno.setBounds(150, 50, 278, 30);

        lblCpfAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpfAluno.setText("Cpf:");
        getContentPane().add(lblCpfAluno);
        lblCpfAluno.setBounds(110, 100, 30, 15);

        lblMatricula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMatricula.setText("Matricula:");
        getContentPane().add(lblMatricula);
        lblMatricula.setBounds(70, 140, 70, 15);

        lblCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCurso.setText("Curso:");
        getContentPane().add(lblCurso);
        lblCurso.setBounds(90, 180, 50, 15);

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setText("Data Cadastro:");
        getContentPane().add(lblData);
        lblData.setBounds(40, 220, 100, 15);

        lblCadastroAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCadastroAlunos.setText("Cadastro de Alunos");
        getContentPane().add(lblCadastroAlunos);
        lblCadastroAlunos.setBounds(200, 20, 140, 15);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(300, 340, 126, 23);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(130, 340, 126, 23);

        txtLogin.setText(" ");
        getContentPane().add(txtLogin);
        txtLogin.setBounds(150, 250, 138, 30);

        txtSenha.setText(" ");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(150, 290, 138, 30);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogin.setText("Login:");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(90, 260, 50, 15);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(80, 300, 60, 15);

        cmbCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Curso", "Engenharia da Computação" }));
        getContentPane().add(cmbCurso);
        cmbCurso.setBounds(150, 170, 200, 30);

        try {
            txtCpfAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpfAluno);
        txtCpfAluno.setBounds(150, 86, 278, 32);

        try {
            txtDataAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDataAluno);
        txtDataAluno.setBounds(150, 206, 278, 32);
        getContentPane().add(txtMat);
        txtMat.setBounds(150, 126, 278, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Renato\\Desktop\\2.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String login =""+txtLogin.getText().trim();
        String senha= ""+txtSenha.getText().trim();
        
        if(cmbCurso.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "Selecione um curso!");
        }
        
        Curso curso = new CursoControle(_bd).GetByNome(cmbCurso.getSelectedItem().toString());
        
        AlunoControle alunoControle= new AlunoControle(_bd);
            
            Aluno aluno=  new Aluno(0,txtNomeAluno.getText().trim(), txtMat.getText().trim(),
                    txtCpfAluno.getText().trim());
            
             if (alunoControle.Create(aluno)) {
                 Usuario usuario= new Usuario(login,senha , TipoUsuario.Aluno);
                 UsuarioControle usuarioControle=new UsuarioControle(_bd);
                 usuarioControle.Create(usuario);
             }

             JOptionPane.showMessageDialog(null, "Aluno "+aluno.getNome()+" Cadastrado com sucesso!");
             
            
            FormInicio sair =new FormInicio(_bd);
                sair.setLocationRelativeTo(null);
                sair.setVisible(true);
                this.dispose();
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       FormInicio sair =new FormInicio(_bd);
       sair.setLocationRelativeTo(null);
       sair.setVisible(true);
       this.dispose();
      
       
    }//GEN-LAST:event_btnSairActionPerformed

    void CarregarCursos()
    {
        
        String curso = "Selecione o curso"; 
        
        cmbCurso.removeAllItems();
        cmbCurso.addItem(curso);
        
        CursoControle cursoControle = new CursoControle(_bd);
        
        for (Curso d: cursoControle.Getall()) {
            cmbCurso.addItem(d.getNome());
        }
    }
    
    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FormCadastroAluno(_bd).setVisible(true);
                
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCadastroAlunos;
    private javax.swing.JLabel lblCpfAluno;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblnome;
    private javax.swing.JFormattedTextField txtCpfAluno;
    private javax.swing.JFormattedTextField txtDataAluno;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
