/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudodirigido.formularios;

import Commum.TipoUsuario;
import javax.swing.JOptionPane;
import estudodirigido.Controle.RepositorioBase;
import estudodirigido.modelo.Aluno;
import estudodirigido.modelo.Usuario;
import estudodirigido.service.AlunoService;
import estudodirigido.service.IAlunoService;
import estudodirigido.service.IUsuarioService;
import estudodirigido.service.UsuarioService;

public class FormInicio extends javax.swing.JFrame {

    IUsuarioService userService = new UsuarioService();
    IAlunoService alunoServive = new AlunoService();
    public static RepositorioBase _bd;
    public static Usuario usuario;

    public FormInicio() {
        try {

            Usuario user = new Usuario("jose.augusto", "1234", TipoUsuario.Aluno);
            Usuario user2 = new Usuario("adm", "1234", TipoUsuario.ADM);
             user =  userService.save(user);
             userService.save(user2);
             
             Aluno aluno = new Aluno(user.getId(),"Jose aluno","00001","36364874851");
             alunoServive.save(aluno);
            //serviceUsuario.save(user);
            initComponents();
            this.setSize(460, 280);
            setLocationRelativeTo(null);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        //this._bd = new RepositorioBase();
    }

    public FormInicio(RepositorioBase bd) {

        initComponents();
        this.setSize(460, 280);
        setLocationRelativeTo(null);
        // this._bd = _bd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(480, 260));
        getContentPane().setLayout(null);
        getContentPane().add(txtLogin);
        txtLogin.setBounds(160, 80, 183, 30);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogin.setText("Login:");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(100, 80, 50, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(100, 130, 50, 20);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(160, 120, 183, 30);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(80, 170, 130, 30);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(250, 170, 130, 30);
        btnCadastrar.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        FormCadastro formCadastro = new FormCadastro(_bd);

        formCadastro.setVisible(true);
        formCadastro.setLocationRelativeTo(null);
        this.dispose();


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        String login = txtLogin.getText();
        String senha = txtSenha.getText();

        try {

            Usuario user = userService.Autenticar(login, senha);

            switch (user.getTipoUsuario()) {

                case ADM:
                        FormCadastro formADM = new FormCadastro(_bd);
                    break;
                case Aluno:
                        FormHomeAluno formAluno = new FormHomeAluno(user);
                        formAluno.setVisible(true);
                        this.dispose();
                    break;
                case Professor:
                    break;
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "erro " + e.getMessage());
        }

        //UsuarioControle usuarioControle = new UsuarioControle(_bd);
//        usuario = usuarioControle.IsValid(login, senha);
//        if (usuario != null) {
//
//            switch ("") {
//                case "Aluno":
//                    FormHomeAluno formAluno = new FormHomeAluno(_bd,usuario);
//                    formAluno.setVisible(true);
//                    this.dispose();
//                    break;
//                case "Professor":
//
//                    FormHomeProfessor formProfessor = new FormHomeProfessor(_bd,usuario);
//                    formProfessor.setVisible(true);
//                    this.dispose();
//                    break;
//            }
//
//        }
//        else{
//            
//            JOptionPane.showMessageDialog(null, "Usuario não cadastrado!");
//        }

    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
