/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudodirigido.formularios;
import Commum.TipoUsuario;
import estudodirigido.Controle.RepositorioBase;
import estudodirigido.Controle.ProfessorControle;
import estudodirigido.Controle.UsuarioControle;
import static estudodirigido.formularios.FormCadastroAluno._bd;
import estudodirigido.modelo.Professor;
import estudodirigido.modelo.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Renato
 */
public class FormCadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastroProfessor
     */
    static int posicaoProf;
    public static RepositorioBase _bd;
    
    public FormCadastroProfessor(RepositorioBase bd) {
        initComponents();
        this.setVisible(true);
        this.setSize(610, 400);
        this.setLocationRelativeTo(null);
        this._bd=bd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCadastroProfessor = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        lblNomeProf = new javax.swing.JLabel();
        txtNomeProf = new javax.swing.JTextField();
        lblEspecialidade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtEspecialidade = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(558, 356));
        getContentPane().setLayout(null);

        lblCadastroProfessor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCadastroProfessor.setText("Cadastro de Professores");
        getContentPane().add(lblCadastroProfessor);
        lblCadastroProfessor.setBounds(200, 30, 160, 15);

        lblRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRegistro.setText("Registro:");
        getContentPane().add(lblRegistro);
        lblRegistro.setBounds(80, 70, 60, 15);
        getContentPane().add(txtRegistro);
        txtRegistro.setBounds(150, 60, 322, 30);

        lblNomeProf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeProf.setText("Nome:");
        getContentPane().add(lblNomeProf);
        lblNomeProf.setBounds(90, 110, 40, 15);
        getContentPane().add(txtNomeProf);
        txtNomeProf.setBounds(150, 100, 322, 30);

        lblEspecialidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEspecialidade.setText("Especialidade:");
        getContentPane().add(lblEspecialidade);
        lblEspecialidade.setBounds(50, 150, 90, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Admissão:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 190, 100, 15);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(110, 320, 117, 29);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(300, 320, 117, 29);
        getContentPane().add(txtEspecialidade);
        txtEspecialidade.setBounds(150, 140, 322, 30);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(80, 270, 60, 15);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogin.setText("Login:");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(90, 230, 50, 15);
        getContentPane().add(txtLogin);
        txtLogin.setBounds(150, 220, 150, 30);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(150, 260, 150, 30);

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtData);
        txtData.setBounds(150, 177, 322, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       String login =""+txtLogin.getText().trim();
        String senha= ""+txtSenha.getText().trim();
        
//         ProfessorControle professorControle = new ProfessorControle(_bd);
////        Professor professor= new Professor(txtNomeProf.getText().trim(), Integer.valueOf(txtRegistro.getText().trim()),
////                txtEspecialidade.getText().trim(), login, senha);
////       
//       
//        if (professorControle.Create(professor)) {
//            Usuario usuario= new Usuario(login,senha , TipoUsuario.Professor
//            );
//                 UsuarioControle usuarioControle=new UsuarioControle(_bd);
//                 usuarioControle.Create(usuario);
//        }
//     
//        JOptionPane.showMessageDialog(null, "Professor "+professor.getNome()+" Cadastrado com sucesso!");
        FormInicio sair =new FormInicio(_bd);
       sair.setLocationRelativeTo(null);
       sair.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       
       FormInicio sair =new FormInicio();
       sair.setLocationRelativeTo(null);
       sair.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroProfessor(_bd).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCadastroProfessor;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNomeProf;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNomeProf;
    private javax.swing.JTextField txtRegistro;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
