/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudodirigido.formularios;


import estudodirigido.Controle.RepositorioBase;
import estudodirigido.modelo.Professor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static estudodirigido.formularios.FormCadastroProfessor.posicaoProf;
import estudodirigido.modelo.Usuario;

/**
 *
 * @author Renato
 */
public class FormHomeProfessor extends javax.swing.JFrame {

    public static RepositorioBase _bd;
    public static Usuario _usuario;
   
    
    public FormHomeProfessor(RepositorioBase bd, Usuario usuario) {
        initComponents();
        this.setSize(647, 490);
        this._bd = bd;
        this._usuario = usuario;
        /*
        lblProf.setText("Nome: "+professores.get(posicaoProf).getNome());
            lblEspecialidade.setText("Especialidade: "+professores.get(posicaoProf).getEspecialidade());
        */
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLancarNota = new javax.swing.JButton();
        btnLancarFaltas = new javax.swing.JButton();
        lblProf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHomeProf = new javax.swing.JTable();
        lblEspecialidade = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnLancarNota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLancarNota.setText("Lançar Notas");
        btnLancarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarNotaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLancarNota);
        btnLancarNota.setBounds(60, 330, 140, 30);

        btnLancarFaltas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLancarFaltas.setText("Lançar Faltas");
        btnLancarFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarFaltasActionPerformed(evt);
            }
        });
        getContentPane().add(btnLancarFaltas);
        btnLancarFaltas.setBounds(380, 330, 140, 30);

        lblProf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblProf.setText("Professor:");
        getContentPane().add(lblProf);
        lblProf.setBounds(21, 11, 160, 14);

        tblHomeProf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ECNTII  ", "101", "DES. TÉC", "NOTURNO"},
                {"ECNTII  ", "107", "CALCULO I", "NOTURNO"},
                {"ECNTVII ", "200", "POO", "NOTURNO"},
                {"ECNTVII ", "295", "BD", "NOTURNO"}
            },
            new String [] {
                "TURMA", "DISCIPLINA", "NOME", "PERIODO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHomeProf.getTableHeader().setReorderingAllowed(false);
        tblHomeProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHomeProfMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHomeProf);
        if (tblHomeProf.getColumnModel().getColumnCount() > 0) {
            tblHomeProf.getColumnModel().getColumn(0).setResizable(false);
            tblHomeProf.getColumnModel().getColumn(1).setResizable(false);
            tblHomeProf.getColumnModel().getColumn(2).setResizable(false);
            tblHomeProf.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(21, 86, 462, 126);

        lblEspecialidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEspecialidade.setText("Especialidade: ");
        getContentPane().add(lblEspecialidade);
        lblEspecialidade.setBounds(249, 11, 270, 14);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 380, 140, 30);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(380, 380, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Renato\\Desktop\\2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancarFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarFaltasActionPerformed
        
            FormFaltas faltas = new FormFaltas();
            faltas.setVisible(true);
            faltas.setLocationRelativeTo(null);
            this.dispose();
        
    }//GEN-LAST:event_btnLancarFaltasActionPerformed

    private void btnLancarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarNotaActionPerformed
         FormNotas notas = new FormNotas();
            notas.setVisible(true);
            notas.setLocationRelativeTo(null);
            this.dispose();
        
    }//GEN-LAST:event_btnLancarNotaActionPerformed

    private void tblHomeProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHomeProfMouseClicked
       
    }//GEN-LAST:event_tblHomeProfMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        FormInicio sair = new FormInicio();
        sair.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

        FormInicio voltar = new FormInicio();
        
        
        voltar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHomeProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHomeProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHomeProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHomeProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHomeProfessor(_bd,_usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancarFaltas;
    private javax.swing.JButton btnLancarNota;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEspecialidade;
    private javax.swing.JLabel lblProf;
    private javax.swing.JTable tblHomeProf;
    // End of variables declaration//GEN-END:variables
}
